apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: otel-log-collector-pod-list
subjects:
- kind: ServiceAccount
  name: otel-log-collector
  namespace: observability
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-list
  apiGroup: rbac.authorization.k8s.io
